### ISSUE TITLE
package.json seems to be missing a babel pre-processor

### ISSUE THREAD

**Issue by awei01** [cerebral/cerebral-testable#2]
Hi,

Trying to run `npm test` after cloning project. I'm getting this error:

```
$ npm test

> cerebral-testable@1.1.0 pretest /work/sandbox/cerebral-testable
> npm run lint --silent


> cerebral-testable@1.1.0 test /work/sandbox/cerebral-testable
> NODE_ENV=test istanbul cover ./node_modules/.bin/_mocha --check-coverage -- -R ${REPORTER:-spec} $(find src -name '*.test.js') || true

No coverage information was collected, exit without writing coverage information
/work/sandbox/cerebral-testable/src/index.test.js:11
      ({ input, state }) => state.set('x', input.x)
       ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/

( truncated )

```

I'm assuming some sort of babel es6 preprocessor should be included in package.json.

**Comment by garth** [comment]
What version of node are you running? Tests should work fine with node 6.

Only the tests are using es2015, everything else should be es5.

**Comment by awei01** [comment]
Yup. You're right. Perhaps add a note to the `readme.md`?
